# FROM selenium/standalone-chrome-debug:3.141.59-zinc
FROM selenium/standalone-chrome-debug:latest

# you can also run this container directly with the command below
# docker run --rm -p 4444:4444 -p 5900:5900 selenium/standalone-chrome-debug:3.141.59-zinc bash -c ". /opt/bin/entry_point.sh"
